In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('messidor_features.artff.csv')

In [3]:
data

attribute0  attribute1  attribute2  attribute3  attribute4  attribute5  \
0              1           1          22          22          22          19   
1              1           1          24          24          22          18   
2              1           1          62          60          59          54   
3              1           1          55          53          53          50   
4              1           1          44          44          44          41   
...          ...         ...         ...         ...         ...         ...   
1146           1           1          34          34          34          33   
1147           1           1          49          49          49          49   
1148           1           0          49          48          48          45   
1149           1           1          39          36          29          23   
1150           1           1           7           7           7           7   

      attribute6  attribute7  attribute8  attribute9  attribute10  \
0             18          14   49.895756   17.775994     5.270920   
1             16          13   57.709936   23.799994     3.325423   
2             47          33   55.831441   27.993933    12.687485   
3             43          31   40.467228   18.445954     9.118901   
4             39          27   18.026254    8.570709     0.410381   
...          ...         ...         ...         ...          ...   
1146          31          24    6.071765    0.937472     0.031145   
1147          45          37   63.197145   27.377668     8.067688   
1148          43          33   30.461898   13.966980     1.763305   
1149          13           7   40.525739   12.604947     4.740919   
1150           7           5   69.423565    7.031843     1.750548   

      attribute11  attribute12  attribute13  attribute14  attribute15  \
0        0.771761     0.018632     0.006864     0.003923     0.003923   
1        0.234185     0.003903     0.003903     0.003903     0.003903   
2        4.852282     1.393889     0.373252     0.041817     0.007744   
3        3.079428     0.840261     0.272434     0.007653     0.001531   
4        0.000000     0.000000     0.000000     0.000000     0.000000   
...           ...          ...          ...          ...          ...   
1146     0.003115     0.000000     0.000000     0.000000     0.000000   
1147     0.979548     0.001552     0.000000     0.000000     0.000000   
1148     0.137858     0.011221     0.000000     0.000000     0.000000   
1149     1.077570     0.563518     0.326860     0.239568     0.174584   
1150     0.046597     0.021180     0.008472     0.000000     0.000000   

      attribute16  attribute17  attribute18  label  
0        0.486903     0.100025            1      0  
1        0.520908     0.144414            0      0  
2        0.530904     0.128548            0      1  
3        0.483284     0.114790            0      0  
4        0.475935     0.123572            0      1  
...           ...          ...          ...    ...  
1146     0.537470     0.116795            0      0  
1147     0.516733     0.124190            0      0  
1148     0.560632     0.129843            0      0  
1149     0.485972     0.106690            1      1  
1150     0.556192     0.088957            0      0  

[1151 rows x 20 columns]

In [4]:
data.describe()

attribute0   attribute1   attribute2   attribute3   attribute4  \
count  1151.000000  1151.000000  1151.000000  1151.000000  1151.000000   
mean      0.996525     0.918332    38.428323    36.909644    35.140747   
std       0.058874     0.273977    25.620913    24.105612    22.805400   
min       0.000000     0.000000     1.000000     1.000000     1.000000   
25%       1.000000     1.000000    16.000000    16.000000    15.000000   
50%       1.000000     1.000000    35.000000    35.000000    32.000000   
75%       1.000000     1.000000    55.000000    53.000000    51.000000   
max       1.000000     1.000000   151.000000   132.000000   120.000000   

        attribute5   attribute6   attribute7   attribute8   attribute9  \
count  1151.000000  1151.000000  1151.000000  1151.000000  1151.000000   
mean     32.297133    28.747176    21.151173    64.096674    23.088012   
std      21.114767    19.509227    15.101560    58.485289    21.602696   
min       1.000000     1.000000     1.000000     0.349274     0.000000   
25%      14.000000    11.000000     8.000000    22.271597     7.939315   
50%      29.000000    25.000000    18.000000    44.249119    17.038020   
75%      48.000000    43.000000    32.000000    87.804112    31.305692   
max     105.000000    97.000000    89.000000   403.939108   167.131427   

       attribute10  attribute11  attribute12  attribute13  attribute14  \
count  1151.000000  1151.000000  1151.000000  1151.000000  1151.000000   
mean      8.704610     1.836489     0.560738     0.212290     0.085674   
std      11.567589     3.923224     2.484111     1.057126     0.398717   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.249050     0.081554     0.000000     0.000000     0.000000   
50%       4.423472     0.484829     0.022248     0.001554     0.000000   
75%      11.766880     1.921648     0.191953     0.038450     0.004832   
max     106.070092    59.766121    51.423208    20.098605     5.937799   

       attribute15  attribute16  attribute17  attribute18        label  
count  1151.000000  1151.000000  1151.000000  1151.000000  1151.000000  
mean      0.037225     0.523212     0.108431     0.336229     0.530843  
std       0.178959     0.028055     0.017945     0.472624     0.499265  
min       0.000000     0.367762     0.057906     0.000000     0.000000  
25%       0.000000     0.502855     0.095799     0.000000     0.000000  
50%       0.000000     0.523308     0.106623     0.000000     1.000000  
75%       0.003851     0.543670     0.119591     1.000000     1.000000  
max       3.086753     0.592217     0.219199     1.000000     1.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1151 entries, 0 to 1150
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   attribute0   1151 non-null   int64  
 1   attribute1   1151 non-null   int64  
 2   attribute2   1151 non-null   int64  
 3   attribute3   1151 non-null   int64  
 4   attribute4   1151 non-null   int64  
 5   attribute5   1151 non-null   int64  
 6   attribute6   1151 non-null   int64  
 7   attribute7   1151 non-null   int64  
 8   attribute8   1151 non-null   float64
 9   attribute9   1151 non-null   float64
 10  attribute10  1151 non-null   float64
 11  attribute11  1151 non-null   float64
 12  attribute12  1151 non-null   float64
 13  attribute13  1151 non-null   float64
 14  attribute14  1151 non-null   float64
 15  attribute15  1151 non-null   float64
 16  attribute16  1151 non-null   float64
 17  attribute17  1151 non-null   float64
 18  attribute18  1151 non-null   int64  
 19  label 

In [6]:
Y = data['label']
Y = np.asarray(Y,dtype=np.int8)

In [7]:
np.unique(Y)

array([0, 1], dtype=int8)

In [8]:
Y.sum()

611

### feature0是图像质量好的意思，只有好的图像

In [9]:
X = data.drop(['attribute0','label'],axis=1)

In [10]:
X = np.asarray(X.values)

### 划分数据集

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2022,stratify=Y)

In [13]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(920, 18)
(920,)
(231, 18)
(231,)


### 标准化

In [12]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [46]:
x_train_nor = scaler.fit_transform(X_train)

In [16]:
#不用归一化
x_train_nor = X_train

### 分类算法

In [14]:
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.model_selection import cross_val_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

#### KNN

In [119]:
# 建立Knn模型
knn = KNeighborsClassifier(n_neighbors=50)

# 使用K折交叉验证模块
scores = cross_val_score(knn, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将5次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.63586957 0.5923913  0.71195652 0.66304348 0.63043478]
0.6467391304347826


In [120]:
knn.fit(x_train_nor, y_train)

KNeighborsClassifier(n_neighbors=50)

In [163]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = knn.predict(x_val_for_test)
accuracy = knn.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)#, average='weighted')
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 70.13%
Precision: 80.00%
Recall: 58.54%
F1: 67.61%


### svm

In [98]:
svc = SVC(C=0.01, gamma=0.001, kernel='linear')

# 使用K折交叉验证模块
scores = cross_val_score(svc, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将5次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.73913043 0.74456522 0.76630435 0.74456522 0.71195652]
0.7413043478260869


In [99]:
svc.fit(x_train_nor, y_train)

SVC(C=0.01, gamma=0.001, kernel='linear')

In [164]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = svc.predict(x_val_for_test)
accuracy = svc.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 73.16%
Precision: 82.80%
Recall: 62.60%
F1: 71.30%


### 随机森林

### 网格搜索

In [122]:
from sklearn.model_selection import GridSearchCV

In [124]:
#首先对n_estimators进行网格搜索  
param_test1= {'n_estimators':range(100,241,20)}  
gsearch1= GridSearchCV(estimator = RandomForestClassifier(min_samples_split=100,  
                                                            min_samples_leaf=20,max_depth=8,max_features='sqrt',),  
                                                            param_grid = param_test1, scoring='accuracy',cv=5)  
gsearch1.fit(x_train_nor, y_train)  

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(max_depth=8, max_features='sqrt',
                                              min_samples_leaf=20,
                                              min_samples_split=100),
             param_grid={'n_estimators': range(100, 241, 20)},
             scoring='accuracy')

In [125]:
print(gsearch1.best_params_)
print(gsearch1.best_score_)

{'n_estimators': 160}
0.6565217391304348


In [127]:
#最大深度max_depth和内部节点再划分所需最小样本数min_samples_split进行网格搜索。
param_test2= {'max_depth':range(3,14,2), 'min_samples_split':range(50,201,20)}  
gsearch2= GridSearchCV(estimator = RandomForestClassifier(n_estimators= 160,  
                                                             min_samples_leaf=20,max_features='sqrt'),  
                                                             param_grid = param_test2,scoring='accuracy',cv=5)
gsearch2.fit(x_train_nor, y_train)  
print(gsearch2.best_params_)
print(gsearch2.best_score_)

{'max_depth': 7, 'min_samples_split': 110}
0.6608695652173913


In [129]:
#再对内部节点再划分所需最小样本数min_samples_split和叶子节点最少样本数min_samples_leaf一起调参 
param_test3= {'min_samples_split':range(80,150,20), 'min_samples_leaf':range(10,60,10)}  
gsearch3= GridSearchCV(estimator = RandomForestClassifier(n_estimators= 160,max_depth=7,  
                                   max_features='sqrt'),  
                                   param_grid = param_test3,scoring='accuracy', cv=5)  
gsearch3.fit(x_train_nor, y_train)
print(gsearch3.best_params_)
print(gsearch3.best_score_)

{'min_samples_leaf': 50, 'min_samples_split': 120}
0.6565217391304348


In [136]:
RF = RandomForestClassifier(n_estimators= 160, max_depth=7, max_features='sqrt', min_samples_leaf=10, min_samples_split=80)
#RF = RandomForestClassifier(n_estimators= 160, max_depth=7, max_features='sqrt', min_samples_leaf=50, min_samples_split=120)

# 使用K折交叉验证模块
scores = cross_val_score(RF, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将5次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.6576087  0.67391304 0.68478261 0.6576087  0.61413043]
0.6576086956521738


In [137]:
RF.fit(x_train_nor, y_train)

RandomForestClassifier(max_depth=7, max_features='sqrt', min_samples_leaf=10,
                       min_samples_split=80, n_estimators=160)

In [165]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = RF.predict(x_val_for_test)
accuracy = RF.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 66.23%
Precision: 72.28%
Recall: 59.35%
F1: 65.18%


### Adaboost

In [18]:
#clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=7, min_samples_leaf=10, min_samples_split=40))
clf = AdaBoostClassifier(SVC(C=0.01, gamma=0.001, kernel='linear'),algorithm='SAMME')
#clf = AdaBoostClassifier(SVC(),algorithm='SAMME')

# 使用K折交叉验证模块
scores = cross_val_score(clf, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将10次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.65217391 0.64673913 0.65217391 0.63043478 0.61956522]
0.6402173913043477


In [19]:
clf.fit(x_train_nor, y_train)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=SVC(C=0.01, gamma=0.001, kernel='linear'))

In [20]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = clf.predict(x_val_for_test)
accuracy = clf.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 68.40%
Precision: 69.53%
Recall: 72.36%
F1: 70.92%


### gradientboost

In [142]:
from sklearn.ensemble import GradientBoostingClassifier

In [143]:
clf_grd = GradientBoostingClassifier(max_depth=7, max_features='sqrt', min_samples_leaf=10,
                                   min_samples_split=40, n_estimators=160, learning_rate=0.05, subsample=0.8)

In [145]:
# 使用K折交叉验证模块
scores = cross_val_score(clf_grd, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将10次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.67934783 0.67391304 0.70652174 0.70108696 0.6576087 ]
0.683695652173913


In [146]:
clf_grd.fit(x_train_nor, y_train)

GradientBoostingClassifier(learning_rate=0.05, max_depth=7, max_features='sqrt',
                           min_samples_leaf=10, min_samples_split=40,
                           n_estimators=160, subsample=0.8)

In [167]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = clf_grd.predict(x_val_for_test)
accuracy = clf_grd.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 71.43%
Precision: 75.22%
Recall: 69.11%
F1: 72.03%


### xgboost

In [148]:
import xgboost as xgb

In [149]:
clf_xgb = xgb.XGBClassifier()

In [150]:
# 使用K折交叉验证模块
scores = cross_val_score(clf_xgb, x_train_nor, y_train, cv=5, scoring='accuracy')

# 将10次的预测准确率打印出
print(scores)

#将5次的预测准确平均率打印出
print(scores.mean())

[0.67934783 0.66847826 0.64673913 0.66304348 0.67391304]
0.6663043478260869


In [151]:
clf_xgb.fit(x_train_nor, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [168]:
x_val_for_test = X_test
#x_val_for_test = scaler.transform(X_test)
Y_actual_val = y_test
Y_pred_val = clf_xgb.predict(x_val_for_test)
accuracy = clf_xgb.score(x_val_for_test, Y_actual_val)  
precision = precision_score(Y_actual_val, Y_pred_val)
recall = recall_score(Y_actual_val, Y_pred_val)
f1 = f1_score(Y_actual_val, Y_pred_val)

print('Accuracy: {:.2f}%'.format(accuracy * 100))
print('Precision: {:.2f}%'.format(precision * 100))
print('Recall: {:.2f}%'.format(recall * 100))
print('F1: {:.2f}%'.format(f1 * 100))

Accuracy: 66.67%
Precision: 69.83%
Recall: 65.85%
F1: 67.78%
